version: 2
updates:
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/packages/docs"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/packages/react-antd-js"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/packages/vue3-antd"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/packages/vue3-element"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/packages/vue3-element-js"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/packages/vue3-vuetify"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    # Look for `package.json` and `lock` files in the `root` directory
    directory: "/libs/logger"
    schedule:
      interval: "weekly"
